experiment_type: "barygnn-PROTEINS"
seed: 42

model:
  version: "v2"
  hidden_dim: 128                   # Unified dimension for encoder output AND codebook atoms
  readout_type: "weighted_mean"     # "weighted_mean" or "concat"
  debug_mode: true
  
  encoder:
    type: "GraphSAGE"               # "GIN" or "GraphSAGE"
    in_dim: 0                       # Will be set based on dataset
    num_layers: 10
    dropout: 0.3
    aggr: "sum"                     # For GraphSAGE
    multi_head_type: "full"         # "full" or "efficient"
    shared_layers: 2                # relevant only for full multi-head encoder
    distribution_size: 16           # Number of vectors per node
    projection_depth: 4             # Number of layers in each projection head (hourglass MLP)
    projection_width_factor: 4.0    # Max width multiplier for hourglass MLP
  
  pooling:
    backend: "geomloss"  # GeomLoss implementation
    codebook_size: 32
    epsilon: 0.2
    p: 2
  
  classification:
    type: "enhanced"                # "simple", "enhanced", "adaptive", "deep_residual"
    dropout: 0.2
    activation: "relu"              # "relu", "leaky_relu", "gelu", "swish"
    norm_type: "batch"              # "batch", "layer", null
    hidden_dims: [256, 128, 64]
    use_residual: true
    residual_type: "add"            # "add", "concat"
    final_dropout: 0.3
    depth_factor: 1.0               # For adaptive
    width_factor: 1.0               # For adaptive
    hidden_dim: 256                 # For deep_residual and simple
    num_blocks: 3                   # For deep_residual
    num_layers: 2                   # For simple
  
  regularization:
    enabled: true
    type: "centroid"                # "variance", "centroid", "coherence"
    lambda_reg: 0.2

data:
  name: "PROTEINS"
  batch_size: 64
  num_workers: 4
  split_seed: 42
  val_ratio: 0.1
  test_ratio: 0.1
  normalize_features: true
  add_self_loops: true

training:
  num_epochs: 300
  lr: 0.05
  weight_decay: 0.0005
  patience: 100
  metric: "accuracy"
  device: "cuda"
  gradient_clip: 1.0
  warmup_epochs: 0

  scheduler: "plateau"
  scheduler_params:
    mode: "max"           # monitor accuracy
    factor: 0.5
    patience: 10
    cooldown: 5           # optional but helpful
    min_lr: 0.0001   


wandb:
  enabled: true
  project: "BaryGNN"
  entity: null
  api_key: 1cf1eb10b27e2214f8d38aa573fdacb7af0ed6c2  # Set via environment variable
  tags: []
  notes: null
  save_code: true
  log_gradients: false
  log_parameters: true
  watch_model: true 