experiment_type: "graph_classification"
seed: 42

model:
  version: "v2"
  hidden_dim: 64
  debug_mode: true
  
  encoder:
    type: "GIN"
    in_dim: 0
    num_layers: 5
    dropout: 0.3
    multi_head_type: "efficient"
    shared_layers: 2
    distribution_size: 32
    projection_depth: 4
    projection_width_factor: 4.0
  
  pooling:
    backend: "barycenter"
    standard_pooling_method: "global_mean_pool"
    readout_type: "weighted_mean"
    codebook_size: 32
    epsilon: 0.2
    p: 2
    scaling: 0.9
  
  classification:
    type: "enhanced"
    hidden_dims: [256, 128, 64]
    dropout: 0.3
    activation: "relu"
    norm_type: "batch"
  
  regularization:
    enabled: true
    type: "variance"
    lambda_reg: 0.02

data:
  name: "MUTAG"
  batch_size: 32
  num_workers: 4
  val_ratio: 0.1
  test_ratio: 0.1
  normalize_features: true
  add_self_loops: true

training:
  num_epochs: 50
  lr: 0.01
  weight_decay: 0.0005
  patience: 20
  metric: "accuracy"
  device: "cuda"
  gradient_clip: 1.0
  
  scheduler: "plateau"
  scheduler_params:
    mode: "max"
    factor: 0.5
    patience: 10
    min_lr: 0.00001

wandb:
  enabled: true
  project: "barygnn_test"
  entity: null
  api_key: 1cf1eb10b27e2214f8d38aa573fdacb7af0ed6c2
  tags: ["barycentric", "MUTAG", "test"]
  notes: "Testing barycentric pooling backend"
  save_code: true
  log_gradients: false
  log_parameters: true
  watch_model: true