experiment_type: "MUTAG_Regular_Pooling"
seed: 42

model:
  version: "v2"
  hidden_dim: 64
  debug_mode: false
  
  encoder:
    type: "GIN"
    in_dim: 7
    num_layers: 3
    dropout: 0.5
    multi_head_type: "efficient"
    shared_layers: 1
    distribution_size: 32
    projection_depth: 2
    projection_width_factor: 1.0
  
  pooling:
    backend: "regular_pooling"
    standard_pooling_method: "global_mean_pool"
  
  classification:
    type: "enhanced"
    hidden_dims: [128, 64]
    dropout: 0.2
    activation: "relu"
    norm_type: "batch"
  
  regularization:
    enabled: true
    type: "variance"
    lambda_reg: 0.01

data:
  name: "MUTAG"
  batch_size: 32
  num_workers: 4
  val_ratio: 0.1
  test_ratio: 0.1
  normalize_features: true
  add_self_loops: true

training:
  num_epochs: 50
  lr: 0.001
  weight_decay: 0.0001
  patience: 20
  metric: "accuracy"
  device: "cuda"
  gradient_clip: 1.0
  
  scheduler: "plateau"
  scheduler_params:
    mode: "max"
    factor: 0.5
    patience: 10
    min_lr: 0.00001

wandb:
  enabled: true
  project: "barygnn_test"
  entity: null
  api_key: <INSERT_API_KEY>
  tags: ["regular_pooling", "MUTAG", "test"]
  notes: "Testing regular pooling backend"
  save_code: true
  log_gradients: false
  log_parameters: true
  watch_model: true