# Optuna study configuration for BaryGNN
study:
  name: barygnn_mutag_opt
  direction: maximize
  storage: sqlite:///barygnn/optuna/optuna.db
  n_trials: 50
  timeout: null
  n_workers: 4  # Number of parallel Optuna workers

base_config: barygnn/config/default_config.yaml

output:
  config_dir: barygnn/config/grid_search_configs
  logs_prefix: grid_search_logs

metric:
  name: accuracy
  mode: max

wandb:
  project_suffix: optuna
  extra_tags: [optuna]

pruning:
  enabled: false
  pruner: median
  warmup_steps: 5

search_space:
  model.hidden_dim:
    type: categorical
    choices: [32, 64, 128]
  model.encoder.num_layers:
    type: categorical
    choices: [3, 5, 8, 12]
  model.pooling.backend:
    type: categorical
    choices: ["barycenter"]
  model.pooling.readout_type:
    type: categorical
    choices: ["weighted_mean"]
  model.pooling.standard_pooling_method:
    type: categorical
    choices: ["global_mean_pool", "global_max_pool", "global_add_pool"]
  model.pooling.codebook_size:
    type: categorical
    choices: [16, 32, 64]
  model.pooling.epsilon:
    type: float
    low: 0.02
    high: 1.0
    log: true
  training.patience:
    type: int
    low: 10
    high: 80
    step: 10
