data:
  add_self_loops: true
  batch_size: 32
  cross_val_mode: false
  custom_test_indices: null
  custom_train_indices: null
  name: PROTEINS
  normalize_features: true
  num_workers: 4
  split_seed: 42
  test_ratio: 0.1
  val_ratio: 0.1
experiment_type: PROTEINS_KFold2
model:
  classification:
    activation: relu
    depth_factor: 1.0
    dropout: 0.2
    final_dropout: 0.5
    hidden_dim: 256
    hidden_dims:
    - 256
    - 128
    - 64
    norm_type: batch
    num_blocks: 3
    num_layers: 2
    residual_type: add
    type: enhanced
    use_residual: true
    width_factor: 1.0
  debug_mode: false
  encoder:
    aggr: mean
    distribution_size: 16
    dropout: 0.026559203088124532
    in_dim: 0
    multi_head_type: efficient
    num_layers: 8
    projection_depth: 1
    projection_width_factor: 0.5997471000820065
    shared_layers: 1
    type: GraphSAGE
    use_categorical_encoding: false
  hidden_dim: 32
  pooling:
    backend: barycenter
    codebook_size: 32
    epsilon: 0.09237495628544681
    p: 2
    readout_type: weighted_mean
    scaling: 0.9
    standard_pooling_method: global_max_pool
  regularization:
    enabled: false
    lambda_reg: 0.02391488404890134
    type: coherence
  version: v2
seed: 42
training:
  class_weights: null
  device: cuda
  focal_alpha: 1.0
  focal_gamma: 2.0
  focal_loss: false
  gradient_clip: 1.0
  lr: 0.006228995633476366
  metric: accuracy
  num_epochs: 300
  patience: 50
  scheduler: plateau
  scheduler_params:
    factor: 0.5
    min_lr: 1.0e-05
    mode: max
    patience: 10
  warmup_epochs: 0
  weight_decay: 0.0020614773065628926
wandb:
  api_key: <INSERT_API_KEY>
  enabled: true
  entity: null
  log_gradients: false
  log_parameters: true
  notes: null
  project: PROTEINS_KFold2
  save_code: true
  watch_model: true
