data:
  add_self_loops: true
  batch_size: 32
  cross_val_mode: false
  custom_test_indices: null
  custom_train_indices: null
  name: MUTAG
  normalize_features: true
  num_workers: 4
  split_seed: 42
  test_ratio: 0.1
  val_ratio: 0.1
experiment_type: MUTAG_KFold
model:
  classification:
    activation: relu
    depth_factor: 1.0
    dropout: 0.2
    final_dropout: 0.5
    hidden_dim: 256
    hidden_dims:
    - 256
    - 128
    - 64
    norm_type: batch
    num_blocks: 3
    num_layers: 2
    residual_type: add
    type: enhanced
    use_residual: true
    width_factor: 1.0
  debug_mode: false
  encoder:
    aggr: mean
    distribution_size: 64
    dropout: 0.21287829107476067
    in_dim: 0
    multi_head_type: efficient
    num_layers: 8
    projection_depth: 3
    projection_width_factor: 1.5797217394556617
    shared_layers: 1
    type: GIN
    use_categorical_encoding: false
  hidden_dim: 32
  pooling:
    backend: barycenter
    codebook_size: 32
    epsilon: 0.09995136570795685
    p: 2
    readout_type: weighted_mean
    scaling: 0.9
    standard_pooling_method: global_add_pool
  regularization:
    enabled: false
    lambda_reg: 0.07264094257477621
    type: coherence
  version: v2
seed: 421
training:
  class_weights: null
  device: cuda
  focal_alpha: 1.0
  focal_gamma: 2.0
  focal_loss: false
  gradient_clip: 1.0
  lr: 0.0013801294191615602
  metric: accuracy
  num_epochs: 300
  patience: 30
  scheduler: plateau
  scheduler_params:
    factor: 0.5
    min_lr: 1.0e-05
    mode: max
    patience: 10
  warmup_epochs: 0
  weight_decay: 0.008479055796679413
wandb:
  api_key: <INSERT_API_KEY>
  enabled: true
  entity: null
  log_gradients: false
  log_parameters: true
  notes: null
  project: MUTAG_KFold
  save_code: true
  watch_model: true
