experiment_name: "barygnn-PROTEINS-hierarchical"
seed: 42

model:
  version: "v2"
  hidden_dim: 128
  readout_type: "weighted_mean"
  debug_mode: false
  
  encoder:
    type: "GraphSAGE"
    in_dim: 0
    num_layers: 6
    dropout: 0.4
    aggr: "sum"
    multi_head_type: "efficient"
    shared_layers: 2
    distribution_size: 12
    projection_depth: 3
    projection_width_factor: 2.0
  
  pooling:
    backend: "hierarchical"  # Hierarchical pooling
    codebook_size: 32
    epsilon_node: 0.3              # Stage 1: Node samples → Node histograms
    epsilon_graph: 0.2             # Stage 2: Node histograms → Graph histogram
    p: 2
  
  classification:
    type: "enhanced"
    dropout: 0.3
    activation: "relu"
    norm_type: "batch"
    hidden_dims: [256, 128, 64]
    use_residual: true
    residual_type: "add"
    final_dropout: 0.4
  
  regularization:
    enabled: true
    type: "coherence"              # Works on node histograms from Stage 1
    lambda_reg: 0.05

data:
  name: "PROTEINS"
  batch_size: 32
  num_workers: 4
  split_seed: 42
  val_ratio: 0.1
  test_ratio: 0.1
  normalize_features: true
  add_self_loops: true

training:
  num_epochs: 200
  lr: 0.05
  weight_decay: 0.001
  patience: 20
  metric: "accuracy"
  device: "cuda"
  gradient_clip: 0.5
  warmup_epochs: 0
  
  scheduler: "plateau"
  scheduler_params:
    mode: "max"
    factor: 0.7
    patience: 15
    min_lr: 0.00001

wandb:
  enabled: true
  project: "BaryGNN-Hierarchical"
  entity: null
  api_key: 1cf1eb10b27e2214f8d38aa573fdacb7af0ed6c2
  tags: ["hierarchical-pooling", "two-stage-ot"]
  notes: "Hierarchical OT pooling with Wasserstein-on-atoms geometry"
  save_code: true
  log_gradients: false
  log_parameters: true
  watch_model: false