# Example Optuna study configuration for BaryGNN
study:
  name: MOLHIV_Opt_Real_1
  direction: maximize
  storage: sqlite:///optuna_studies
  n_trials: 10
  timeout: null
  n_workers: 1  # Number of parallel Optuna workers

base_config: barygnn/config/benchmark_configs/MOLHIV/barycentric_molhiv_config.yaml

metric:
  name: roc_auc
  mode: max

wandb:
  enabled: true
  project: MOLHIV_Opt_Real_1
  project_suffix: optuna
  extra_tags: [optuna]

pruning:
  enabled: false
  pruner: median
  warmup_steps: 5


search_space:
  model.encoder.type:
    type: categorical
    choices: ["GIN", "GraphSAGE"]
  model.hidden_dim:
    type: categorical
    choices: [32, 64, 128]
  model.encoder.num_layers:
    type: categorical
    choices: [3, 5, 8]
  model.encoder.dropout:
    type: float
    low: 0.001
    high: 0.5
    log: true
  model.encoder.shared_layers:
    type: categorical
    choices: [1, 2]
  model.encoder.distribution_size:
    type: categorical
    choices: [16, 32, 64]
  model.encoder.projection_depth:
    type: categorical
    choices: [1, 2, 3]
  model.encoder.projection_width_factor:
    type: float
    low: 0.5
    high: 2.0
    log: true

  model.pooling.standard_pooling_method:
    type: categorical
    choices: ["global_mean_pool", "global_add_pool", "global_max_pool"]
  model.pooling.readout_type:
    type: categorical
    choices: ["weighted_mean", "concat"]
  model.pooling.codebook_size:
    type: categorical
    choices: [16, 32, 64]
  model.pooling.epsilon:
    type: float
    low: 0.05
    high: 0.5
    log: true

  model.regularization.enabled:
    type: categorical
    choices: [true, false]
  model.regularization.type:
    type: categorical
    choices: ["variance", "centroid", "coherence"]
  model.regularization.lambda_reg:
    type: float
    low: 0.001
    high: 0.2
    log: true