# Example Optuna study configuration for BaryGNN
study:
  name: &study_name ENZYMES_Opt_Real_Refined_1
  direction: maximize
  storage: sqlite:///optuna_studies
  n_trials: 60
  timeout: null
  n_workers: 1  # Number of parallel Optuna workers

base_config: barygnn/config/benchmark_configs/ENZYMES/refined/barycentric_enzymes_config.yaml

metric:
  name: accuracy
  mode: max

wandb:
  enabled: true
  project: *study_name
  project_suffix: optuna
  extra_tags: [optuna]

pruning:
  enabled: false
  pruner: median
  warmup_steps: 5

search_space:
  model.encoder.type:
    type: categorical
    choices: ["GraphSAGE"]
  model.hidden_dim:
    type: categorical
    choices: [32, 64, 128]
  model.encoder.num_layers:
    type: categorical
    choices: [4, 5, 6]
  model.encoder.dropout:
    type: float
    low: 0.01
    high: 0.5
    log: true
  model.encoder.shared_layers:
    type: categorical
    choices: [1, 2]
  model.encoder.distribution_size:
    type: categorical
    choices: [16, 32, 64]
  model.encoder.projection_depth:
    type: categorical
    choices: [1, 2, 3]
  model.encoder.projection_width_factor:
    type: float
    low: 0.5
    high: 2.0
    log: true

  model.pooling.standard_pooling_method:
    type: categorical
    choices: ["global_mean_pool", "global_add_pool"]
  model.pooling.readout_type:
    type: categorical
    choices: ["weighted_mean", "concat"]
  model.pooling.codebook_size:
    type: categorical
    choices: [16, 32, 64]
  model.pooling.epsilon:
    type: float
    low: 0.1
    high: 0.5
    log: true

  model.regularization.enabled:
    type: categorical
    choices: [true, false]
  model.regularization.type:
    type: categorical
    choices: ["variance", "centroid"]
  model.regularization.lambda_reg:
    type: float
    low: 0.01
    high: 0.2
    log: true


  training.lr:
    type: float
    low: 0.003
    high: 0.006
    log: true
  training.weight_decay:
    type: float
    low: 0.004
    high: 0.009
    log: false
  training.patience:
    type: int
    low: 30
    high: 45
    step: 5