data:
  add_self_loops: true
  batch_size: 32
  cross_val_mode: false
  custom_test_indices: null
  custom_train_indices: null
  name: IMDB-BINARY
  normalize_features: true
  num_workers: 4
  split_seed: 42
  test_ratio: 0.1
  val_ratio: 0.1
experiment_type: IMDB_B_KFold
model:
  classification:
    activation: relu
    depth_factor: 1.0
    dropout: 0.2
    final_dropout: 0.5
    hidden_dim: 256
    hidden_dims:
    - 256
    - 128
    - 64
    norm_type: batch
    num_blocks: 3
    num_layers: 2
    residual_type: add
    type: enhanced
    use_residual: true
    width_factor: 1.0
  debug_mode: false
  encoder:
    aggr: mean
    distribution_size: 64
    dropout: 0.029322647782781652
    in_dim: 0
    multi_head_type: efficient
    num_layers: 8
    projection_depth: 2
    projection_width_factor: 1.2753897888789774
    shared_layers: 1
    type: GraphSAGE
    use_categorical_encoding: false
  hidden_dim: 80
  pooling:
    backend: barycenter
    codebook_size: 112
    epsilon: 0.14940259659527624
    p: 2
    readout_type: weighted_mean
    scaling: 0.9
    standard_pooling_method: global_add_pool
  regularization:
    enabled: true
    lambda_reg: 0.01374472005186366
    type: centroid
  version: v2
seed: 421
training:
  class_weights: null
  device: cuda
  focal_alpha: 1.0
  focal_gamma: 2.0
  focal_loss: false
  gradient_clip: 1.0
  lr: 0.00027297880091847624
  metric: accuracy
  num_epochs: 300
  patience: 40
  scheduler: plateau
  scheduler_params:
    factor: 0.5
    min_lr: 1.0e-05
    mode: max
    patience: 10
  warmup_epochs: 0
  weight_decay: 0.005448812106180202
wandb:
  api_key: 1cf1eb10b27e2214f8d38aa573fdacb7af0ed6c2
  enabled: true
  entity: null
  log_gradients: false
  log_parameters: true
  notes: null
  project: IMDB_B_KFold
  save_code: true
  tags:
  - kfold
  watch_model: true
